name: syncstorage-rs-mysql

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * 1'
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # generic variables
      REPOSITORY_SITE: ghcr.io
      REPOSITORY_FULL_NAME: ${{ github.repository }}
      SERVICE_NAME: syncstorage-rs
      SERVICE_REPOSITORY: https://github.com/mozilla-services/syncstorage-rs
      CHANGELOG_PATH: CHANGELOG.md
      IMAGE_EXPIRY: 600000 # in seconds, slightly less than a week
      IMAGE_PREFIX_TAGS: mysql-
      SERVICE_REQUIRE_INIT: true
      # specific for this component
      DATABASE_BACKEND: mysql

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ... (rest of your steps)

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ${{ env.REPOSITORY_SITE }} -u "${{ github.actor }}" --password-stdin

      # ... (rest of your steps)
